name: Get measurements from Airly

on:
  workflow_dispatch:
  schedule:
    # Runs "10 pm every day" (see https://crontab.guru)
    - cron: "0 22 * * *"

jobs:
  get_measurements:
    name: Get measurements from Airly
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - name: install dependencies
        run: |
          python -m pip install -r scripts/requirements.txt

      - name: setup API keys
        shell: bash
        env:
          API_KEYS: ${{ secrets.API_KEYS }}
        run: |
          echo "$API_KEYS" > Airly_API.json

      - name: execute py script # run the get_measurements.py to get the latest data
        run: |
          python scripts/get_measurements.py

      - name: commit changes
        run: |
          git config user.name 'github-action'
          git config user.email 'github-actions@github.com'
          git add ./data
          git commit -m "Automated measurements commit"
          git push

      - name: update csv
        run: |
          python scripts/generate_csv.py

      - name: compress new raw data
        shell: bash
        run: |
          ls -d data/raw/* | grep -v .tar.gz | xargs -I {} tar -zcf {}.tar.gz {}
          ls -d data/raw/* | grep -v .tar.gz | xargs -I {} sh -c 'cat {}.tar.gz >> $(echo {} | sed "s|\/[0-9]*-|/|g").tar.gz && rm {}.tar.gz'
          ls -d data/raw/* | grep -v .tar.gz | xargs rm -rf

      - name: commit changes
        run: |
          git config user.name 'github-action'
          git config user.email 'github-actions@github.com'
          git add ./data
          git commit -m "Automated measurements commit"
          git push
